### PR TITLE
fix: psycopg2-binary version fix

### LINKED ISSUE #1170: Change in Requirement.txt for psycopg2-binary
### Describe the bug
psycopg2-binary == 2.8.6 is throwing an error - "The license_file parameter is deprecated, use license_files instead." , when installing requirements

### To Reproduce
1. Clone repository
2. create virtaul env and install requirements: pip install -r requirement
3. See error

### Expected behavior
It should install requirements without any error.

### Screenshots
Screenshot 2023-07-06 at 11 08 36 PM

### Desktop (please complete the following information):
 - OS: Mac 

### Additional context
This is issue with the library psycopg2-binary, which has been update 2 months before.  To solve the issue we just need to make,
psycopg2-binary == 2.9.6

Screenshot 2023-07-06 at 11 13 22 PM

### PR DESCRIPTION
**Pull request by Raghunandhan8818**
### Description

**Issue**: The previous version of `psycopg2-binary` (2.8.6) was throwing an error during installation, stating "The license_file parameter is deprecated, use license_files instead."

**Solution**: After conducting thorough research, I upgraded the `psycopg2-binary` library to version 2.9.6, which resolved the aforementioned issue. And I have specified the latest version (`3.3.3`) for the package `pre-commit` so that there wont be any version conflicts in future as well. For the second issue , I have upgraded all the dependencies so that the projects runs without any errors.

Fixes #1170 and #1153

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

 I have tested the above installation by running `pip install -r requirements.txt` , and it gave no errors. All the dependencies installed successfully.

Below is the result before version upgradation.
Screenshot from 2023-08-25 21-22-46

Result after version upgradation. All the dependencies installed successfully !
image

I have updated the dependencies and the projects works without any error !!

image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Update requirements.txt

**Code/Quality Assurance Only**

- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Raghunandhan8818** [comment]
Hello @isabelcosta ! This is my first try to the open source contribution and would love to contribute to this project. Let me know if I have to do anything else to get this PR merged.

**Comment by Raghunandhan8818** [comment]
Hello @isabelcosta  @vj-codes !

I was working on the dependencies and now everything works fine on python 3.7. There was problem with `Jinja2` and `Psycopg2-Binary` .When I submitted my PR ,all the dependencies were installed successfully but it is throwing error in running the tests as `TypeError: delete() got an unexpected keyword argument 'request_id'` . 

Shall I work on resolving those errors as well ? What should I do now ? 

image
